parameters:
    cms_version: 1.2.0

twig:
    globals:
        cms_version: %cms_version%
    form:
        resources:
            - 'bootstrap_3_layout.html.twig'

    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    base_template_class: Sonata\CacheBundle\Twig\TwigTemplate14

doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType