parameters:
    cms_version: 1.2.4

twig:
    globals:
        cms_version: %cms_version%

    form_themes:
        - 'VichUploaderBundle:Form:fields.html.twig'

    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'
            - 'bootstrap_3_layout.html.twig'

    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    base_template_class: Sonata\CacheBundle\Twig\TwigTemplate14

doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
