cmf_routing:
    chain:
        routers_by_id:
            # enable the DynamicRouter with high priority to allow overwriting configured routes with content
            #cmf_routing.dynamic_router: 200
            # enable the symfony default router with a lower priority
            sonata.page.router: 150
            router.default: 100

sonata_page:
#    Pour la version suivante
#    slugify_service:  sonata.core.slugify.cocur # old BC value is sonata.core.slugify.native

    class:
        page:     Application\Th3Mouk\CMSPageBundle\Entity\Page
        snapshot: Application\Th3Mouk\CMSPageBundle\Entity\Snapshot
        block:    Application\Th3Mouk\CMSPageBundle\Entity\Block
        site:     Application\Th3Mouk\CMSPageBundle\Entity\Site
